language: c++

compiler: g++

matrix:
  include:
   - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"
    
install:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libboost-dev

script: make
