language: cxx

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  - CXX=g++-6
    
install:
  - sudo apt-get install libsfml-dev
  - sudo apt-get install libboost-dev

script: make
